package com.airbnb.android.showkase.models

/**
 * Interface implemented by the final class that's autogenerated by the ShowkaseProcessor. User's
 * of this library don't need to use this as it's for internal usage only.
 */
// 实际的 Showcase 的内部 API 说明，有哪些能力。
interface ShowkaseProvider {
    fun getShowkaseComponents(): List<ShowkaseBrowserComponent>

    // 作为扩展的需求，弥补 `@preview` 支持的有限参数？
    fun getShowkaseColors(): List<ShowkaseBrowserColor>
    
    // 作为扩展的需求，弥补 `@preview` 支持的有限参数？
    fun getShowkaseTypography(): List<ShowkaseBrowserTypography>
    
    // 获取描述信息
    fun metadata(): ShowkaseElementsMetadata {
        val componentList = getShowkaseComponents()
        val colorList = getShowkaseColors()
        val typographyList = getShowkaseTypography()
        return ShowkaseElementsMetadata(componentList, colorList, typographyList)
    }
}
